customization:
  extraKernelArgs:
    - amd_iommu=on
    - mitigations=off
    - net.ifnames=0
    - amdgpu.gttsize=122800
    - amdgpu.vm_fragment_size=8
    - ttm.pages_limit=31457280
    - ttm.page_pool_size=25165824
  systemExtensions:
    officialExtensions:
      - siderolabs/fuse3
      - siderolabs/amd-ucode
      - siderolabs/amdgpu
      - siderolabs/thunderbolt
