customization:
  extraKernelArgs:
    - amd_iommu=off
    - amdgpu.gttsize=126976
    - amdgpu.vm_fragment_size=8
    - ttm.pages_limit=32505856
    - ttm.page_pool_size=25165824
    - amdttm.pages_limit=32505856
    - amdttm.page_pool_size=25165824
  systemExtensions:
    officialExtensions:
      - siderolabs/fuse3
      - siderolabs/amd-ucode
      - siderolabs/amdgpu
      - siderolabs/thunderbolt
