apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: servarr
  annotations:
    argocd.argoproj.io/sync-wave: "23"
spec:
  selector:
    app: sabnzbd
  ports:
    - name: webui
      targetPort: 8080
      port: 8080
