apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qdrant-common
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "17"
spec:
  destination:
    namespace: qdrant
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/blake-hamm/bhamm-lab.git
    targetRevision: main
    path: kubernetes/charts/common
    helm:
      valuesObject:
        name: qdrant
        ingressRoutes:
          - name: qdrant
            ingressClass: traefik-external
            websocket: true
            routes:
              - match: Host(`qdrant.bhamm-lab.com`)
                kind: Rule
                priority: 10
                services:
                  - name: qdrant
                    scheme: http
                    port: http
              - kind: Rule
                match: Host(`qdrant.bhamm-lab.com`) && Header(`Content-Type`, `application/grpc`)
                priority: 11
                services:
                  - name: qdrant
                    port: grpc
                    scheme: h2c
        externalSecrets:
          enabled: true
          secrets:
            - secretKey: API_KEY
              remoteRef:
                key: /default/qdrant
                property: API_KEY
        pvc:
          - name: qdrant-storage-qdrant-0
            storageSize: 10Gi
        k8up:
          backup:
            enabled: true
          restore:
            enabled: true
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
