baseURL: https://site.bhamm-lab.com/
languageCode: en-us
title: Blake Hamm
theme: PaperMod
params:
  description: "My personal website"
  author: "Blake Hamm"
  assets:
    favicon: "/favicon.jpg"
  profileMode:
    enabled: true
    title: "Hi! I'm Blake."
    subtitle: "This is my digital record of open source projects, opinions on AI/ML engineering and the occasional adventure story."
    imageUrl: "/headshot.jpg"
    imageWidth: 40%
    imageHeight: 40%
    buttons:
      - name: About
        url: /about
      - name: Portfolio
        url: /portfolio
      - name: Blogs
        url: /blogs
      - name: Docs
        url: https://docs.bhamm-lab.com/
  # PaperMod options
  ShowShareButtons: false
  ShowPostNavLinks: true
  socialIcons:
    - name: "github"
      url: "https://github.com/blake-hamm"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/blakejhamm/"
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: portfolio
      name: Portfolio
      url: /portfolio/
      weight: 2
    - identifier: blogs
      name: Blogs
      url: /blogs/
      weight: 3
    - identifier: docs
      name: Docs
      url: https://docs.bhamm-lab.com/
      weight: 4
