baseURL: https://bhamm-lab.com/
languageCode: en-us
title: Blake Hamm
theme: PaperMod
params:
  description: "My personal website"
  author: "Blake Hamm"
  assets:
    favicon: "/favicon.jpg"
  profileMode:
    enabled: true
    title: "Blake Hamm"
    subtitle: "Welcome to my corner of the internet!"
    imageUrl: "/favicon.jpg"
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: Blogs
        url: /blogs
      - name: Portfolio
        url: /portfolio
      - name: About
        url: /about
      - name: Contact
        url: /contact
  # PaperMod options
  ShowShareButtons: true
  ShowPostNavLinks: true
  socialIcons:
    - name: "github"
      url: "https://github.com/blake-hamm"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/blakejhamm/"
menu:
  main:
    - identifier: blogs
      name: Blogs
      url: /blogs/
      weight: 10
    - identifier: portfolio
      name: Portfolio
      url: /portfolio/
      weight: 20
    - identifier: about
      name: About
      url: /about/
      weight: 30
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 40
