apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: docs-tunnel-binding
  namespace: docs
  annotations:
    argocd.argoproj.io/sync-wave: "22"
subjects:
  - name: http://docs-site.docs.svc.cluster.local:80
tunnelRef:
  kind: ClusterTunnel
  name: external-tunnel
