apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: docs-tunnel-binding
  namespace: docs
  annotations:
    argocd.argoproj.io/sync-wave: "25"
subjects:
  - name: docs-site
    spec:
      target: http://docs-site.docs.svc.cluster.local:80
      fqdn: docs.bhamm-lab.com
tunnelRef:
  kind: ClusterTunnel
  name: external-tunnel
