- name: Forward vpn queries
  oxlorg.opnsense.unbound_forward:
    domain: 'vpn.bhamm-lab.com'
    target: '1.1.1.1'
- name: Forward docs queries
  oxlorg.opnsense.unbound_forward:
    domain: 'docs.bhamm-lab.com'
    target: '1.1.1.1'
