apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-common
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  destination:
    namespace: cloudflare-operator-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/blake-hamm/bhamm-lab.git
    targetRevision: main
    path: kubernetes/charts/common
    helm:
      valuesObject:
        name: cloudflare
        externalSecrets:
          enabled: true
          secrets:
            - secretKey: cloudflare-token
              remoteRef:
                key: /external/cloudflare
                property: cloudflare-token
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
