apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-monitor-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "19"
spec:
  destination:
    namespace: cloudflare-monitor
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/blake-hamm/bhamm-lab.git
    targetRevision: main
    path: kubernetes/charts/common
    helm:
      valuesObject:
        name: cloudflare-monitor
        externalSecrets:
          enabled: true
          secrets:
            - secretKey: CF_API_TOKEN
              remoteRef:
                key: /external/cloudflare
                property: cloudflare-token
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-monitor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  destination:
    namespace: cloudflare-monitor
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://lablabs.github.io/cloudflare-exporter
    chart: cloudflare-exporter
    targetRevision: 0.2.2
    helm:
      valuesObject:
        image:
          tag: "0.2.3"
        secretRef: "cloudflare-monitor-external-secret"
        env:
          - name: FREE_TIER
            value: "true"
        serviceMonitor:
          enabled: true
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
