apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: twenty-common
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  destination:
    namespace: twenty
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/blake-hamm/bhamm-lab.git
    targetRevision: main
    path: kubernetes/charts/common
    helm:
      valuesObject:
        name: twenty
        postgresql:
          enabled: true
          backup:
            enabled: true
          restore:
            enabled: false
        dragonfly:
          enabled: true
        pvc:
          - name: twenty-local-data
            storageSize: 10Gi
        k8up:
          backup:
            enabled: true
          restore:
            enabled: false
        externalSecrets:
          enabled: true
          secrets:
            - secretKey: APP_SECRET
              remoteRef:
                key: /default/twenty
                property: APP_SECRET
        ingressRoutes:
          - name: twenty
            ingressClass: traefik-external
            websocket: true
            routes:
              - match: Host(`crm.bhamm-lab.com`)
                kind: Rule
                middlewares:
                  - name: default-headers
                services:
                  - name: twenty-server
                    scheme: http
                    port: 3000
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
