apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: models-common
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "18"
spec:
  destination:
    namespace: models
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/blake-hamm/bhamm-lab.git
    targetRevision: main
    path: kubernetes/charts/common
    helm:
      valuesObject:
        name: models
        ingressRoutes:
          - name: glm-air
            ingressClass: traefik-external
            routes:
              - match: Host(`glm-air.bhamm-lab.com`)
                kind: Rule
                middlewares:
                  - name: default-headers
                services:
                  - name: glm-air
                    scheme: http
                    port: http
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
