apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llm-models-common
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "17"
spec:
  destination:
    namespace: models
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/blake-hamm/bhamm-lab.git
    targetRevision: main
    path: kubernetes/charts/common
    helm:
      valuesObject:
        name: models
        externalSecrets:
          enabled: true
          secrets:
            - secretKey: hf_token
              remoteRef:
                key: /default/llm-models
                property: hf_token
        postgresql:
          enabled: true
          backup:
            enabled: true
          restore:
            enabled: false
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
