apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llm-models-common
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "17"
spec:
  destination:
    namespace: models
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/blake-hamm/bhamm-lab.git
    targetRevision: main
    path: kubernetes/charts/common
    helm:
      valuesObject:
        name: models
        externalSecrets:
          enabled: true
          secrets:
            - secretKey: hf_token
              remoteRef:
                key: /default/llm-models
                property: hf_token
            - secretKey: access_key_id
              remoteRef:
                key: /core/seaweedfs
                property: admin_access_key_id
            - secretKey: secret_access_key
              remoteRef:
                key: /core/seaweedfs
                property: admin_secret_access_key
        postgresql:
          enabled: true
          backup:
            enabled: true
          restore:
            enabled: false
        ingressRoutes:
          - name: mlflow
            ingressClass: traefik-external
            websocket: true
            routes:
              - match: Host(`mlflow.bhamm-lab.com`)
                kind: Rule
                middlewares:
                  - name: default-headers
                  - name: forwardauth-authelia
                services:
                  - name: llm-models-mlflow
                    scheme: http
                    port: http
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
