apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
  namespace: servarr
  labels:
    app: nzbget
  annotations:
    argocd.argoproj.io/sync-wave: "22"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nzbget
  template:
    metadata:
      labels:
        app: nzbget
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: gluetun
          image: ghcr.io/qdm12/gluetun:v3.39.0
          env:
            - name: VPN_SERVICE_PROVIDER
              value: protonvpn
            - name: VPN_TYPE
              value: wireguard
            - name: VPN_PORT_FORWARDING
              value: "off"
            - name: VPN_PORT_FORWARDING_PROVIDER
              value: protonvpn
            - name: SERVER_COUNTRIES
              value: "United States"
            - name: TZ
              value: "America/Denver"
            - name: FIREWALL_INPUT_PORTS
              value: "6789"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.96.0.0/12,10.244.0.0/16,10.42.0.0/16"
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: servarr-external-secret
                  key: WIREGUARD_PRIVATE_KEY
          securityContext:
            runAsUser: 0
            capabilities:
              add:
                - NET_ADMIN
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: gluetun-config
              mountPath: /gluetun
        - name: nzbget
          image: lscr.io/linuxserver/nzbget:latest
          ports:
            - containerPort: 6789
              name: web-ui
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Denver"
            - name: NZBGET_USER
              valueFrom:
                secretKeyRef:
                  name: servarr-external-secret
                  key: NZBGET_USER
            - name: NZBGET_PASS
              valueFrom:
                secretKeyRef:
                  name: servarr-external-secret
                  key: NZBGET_PASS
          volumeMounts:
            - name: nzbget-config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: gluetun-config
          persistentVolumeClaim:
            claimName: nzbget-gluetun-config
        - name: nzbget-config
          persistentVolumeClaim:
            claimName: nzbget-config
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads
