apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actual-budget-common
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  destination:
    namespace: actual-budget
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/blake-hamm/bhamm-lab.git
    targetRevision: main
    path: kubernetes/charts/common
    helm:
      valuesObject:
        name: actual-budget
        ingressRoutes:
          - enabled: true
            name: immich
            ingressClass: traefik-external
            routes:
              - match: Host(`actual-budget.bhamm-lab.com`)
                kind: Rule
                services:
                  - name: actual-budget
                    port: 5006
                    scheme: http
        externalSecrets:
          enabled: true
          secrets:
            - secretKey: ACTUAL_OPENID_CLIENT_SECRET
              remoteRef:
                key: /default/actual-budget
                property: ACTUAL_OPENID_CLIENT_SECRET
        pvc:
          - name: actual-budget-data
            size: 5Gi
        k8up:
          backup:
            enabled: true
          restore:
            enabled: false
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
