collections:
  - name: community.hashi_vault
    version: "6.2.0"
    source: https://galaxy.ansible.com
  - name: devsec.hardening
    version: "10.0.0"
    source: https://galaxy.ansible.com
  - name: oxlorg.opnsense
    version: "25.7.7"
    source: https://galaxy.ansible.com
  - name: community.sops
    version: "2.0.1"
    source: https://galaxy.ansible.com
  - name: prometheus.prometheus
    version: "0.25.0"
    source: https://galaxy.ansible.com
  - name: grafana.grafana
    version: "5.7.0"
    source: https://galaxy.ansible.com
roles:
  - name: geerlingguy.ntp
    version: "2.5.0"
  - src: https://github.com/lae/ansible-role-proxmox.git
    name: lae.proxmox
    version: "v1.9.4"
