apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ./unpackarr/base
  - ./prowlarr/base
  - ./radarr/base
  - ./flaresolverr/base
  - ./qbittorent/base
  - ./sonarr/base
  - ./jellyfin/base
  - ./nzbget/base
  - ./recyclarr/base
  - ./cleanuparr/base
  - ./huntarr/base
  - ./jellyseerr/base
